# Generated by Django 4.2.2 on 2023-06-28 11:47

import core.util.model_to_dict
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('MNTR', 'Monitor'), ('CTRL', 'Control'), ('SECU', 'Security')], max_length=100, null=True)),
                ('status', models.JSONField(max_length=100, null=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.rooms')),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
            bases=(models.Model, core.util.model_to_dict.ModelToDictionary),
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.devices')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.rooms')),
            ],
            options={
                'db_table': 'channels',
                'managed': True,
            },
            bases=(models.Model, core.util.model_to_dict.ModelToDictionary),
        ),
    ]
