# Generated by Django 4.2.2 on 2023-07-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_homes_id_alter_homeuseraccess_id_and_more'),
        ('devices', '0002_remove_channels_type_remove_devices_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='pin',
        ),
        migrations.AlterField(
            model_name='channels',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.rooms'),
        ),
    ]
