# Generated by Django 3.2 on 2023-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_devices_pin_alter_channels_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
