# Generated by Django 3.2 on 2023-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
