# Generated by Django 3.2 on 2023-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20230830_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
