# Generated by Django 3.2 on 2023-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devices_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
