# Generated by Django 4.2.2 on 2023-06-28 11:48

import core.util.model_to_dict
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Homes',
                'managed': True,
            },
            bases=(models.Model, core.util.model_to_dict.ModelToDictionary),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
            ],
            options={
                'db_table': 'Rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomeUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'HomeUserAccess',
                'managed': True,
            },
            bases=(models.Model, core.util.model_to_dict.ModelToDictionary),
        ),
    ]
