# Generated by Django 4.2.2 on 2023-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_homes_id_alter_homeuseraccess_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
