# Generated by Django 4.2.2 on 2023-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_homes_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeuseraccess',
            name='role',
            field=models.BooleanField(default=0),
        ),
    ]
