# Generated by Django 4.2.2 on 2023-07-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_homeuseraccess_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homes',
            table='homes',
        ),
        migrations.AlterModelTable(
            name='homeuseraccess',
            table='home_user_access',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
    ]
