# Generated by Django 3.2 on 2023-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_alter_homes_table_alter_homeuseraccess_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeuseraccess',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
