# Generated by Django 3.2 on 2023-11-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_id'),
        ('homes', '0006_homeuseraccess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
    ]
