# Generated by Django 3.2 on 2023-11-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_homes_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homes',
            old_name='created_by',
            new_name='created_by_id',
        ),
    ]
