# Generated by Django 3.2 on 2023-11-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_rename_created_by_homes_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homes',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
