# Generated by Django 3.2 on 2023-11-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_id'),
        ('homes', '0009_rename_created_by_id_homes_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
