# Generated by Django 4.2.2 on 2023-07-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
